name: Castle
main: turbo.castle.Castle
version: '${version}'
api-version: '1.12.2'
commands:
  base:
    description: tp base
    usage: /<command>
  wood:
    description: wood info
    usage: /<command>
  stone:
    description: stone info
    usage: /<command>
  wave:
    description: start wave
    usage: /<command>
  test:
    description: test command
    usage: /<command>
  woodPVP:
    description: wave wood
    usage: /<command>
  stonePVP:
    description: wave stone
    usage: /<command>
  townHallInfo:
    description: townHall info
    usage: /<command>
  woodPVE:
    description: farm wood
    usage: /<command>
  stonePVE:
    description: farm stone
    usage: /<command>